name: coursepick-prod-db

services:
  mongodb:
    image: mongo:8.0.12
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME='
      - 'MONGO_INITDB_ROOT_PASSWORD='
      - 'MONGO_INITDB_DATABASE='
    volumes:
      - /var/lib/coursepick/mongodb:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      - 'ME_CONFIG_MONGODB_SERVER=mongodb'
      - 'ME_CONFIG_MONGODB_PORT=27017'
      - 'ME_CONFIG_MONGODB_ENABLE_ADMIN='
      - 'ME_CONFIG_MONGODB_AUTH_USERNAME='
      - 'ME_CONFIG_MONGODB_AUTH_PASSWORD='
      - 'ME_CONFIG_BASICAUTH_USERNAME='
      - 'ME_CONFIG_BASICAUTH_PASSWORD='
    depends_on:
      mongodb:
        condition: service_healthy

  mysql:
    image: 'mysql:8.4.5'
    environment:
      - 'MYSQL_DATABASE=???'
      - 'MYSQL_ROOT_PASSWORD=???'
      - 'MYSQL_USER=???'
      - 'MYSQL_PASSWORD=???'
      - 'LANG=C.UTF-8'
      - 'LC_ALL=C.UTF-8'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
