services:
  backend:
    image: coursepicks/coursepick-backend:prod
    container_name: coursepick-backend
    ports:
      - '80:8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=${PROD_PROFILE}'
      - 'DB_URL=${PROD_DB_URL}'
      - 'DB_USERNAME=${PROD_DB_USERNAME}'
      - 'DB_PASSWORD=${PROD_DB_PASSWORD}'
      - 'MONGO_HOST=${PROD_MONGO_HOST}'
      - 'MONGO_PORT=${PROD_MONGO_PORT}'
      - 'MONGO_DATABASE=${PROD_MONGO_DATABASE}'
      - 'MONGO_USERNAME=${PROD_MONGO_USERNAME}'
      - 'MONGO_PASSWORD=${PROD_MONGO_PASSWORD}'
      - 'MONGO_AUTH_DATABASE=${PROD_MONGO_AUTH_DATABASE}'
      - 'ADMIN_TOKEN=${ADMIN_TOKEN}'
      - 'GCP_DRIVE_FOLDER_ID=${GCP_DRIVE_FOLDER_ID}'
      - 'GCP_CREDENTIALS_PATH=${GCP_CREDENTIALS_PATH}'
    volumes:
      - /var/lib/coursepick/logs:/var/lib/coursepick/logs
    restart: unless-stopped
