name: coursepick-prod-server
services:

  backend:
    image: coursepicks/coursepick-backend:prod
    container_name: coursepick-backend
    ports:
      - '80:8080'
    env_file:
      - .env
    volumes:
      - /var/lib/coursepick/logs:/var/lib/coursepick/logs
      - /var/lib/coursepick/gcp-credentials.json:/var/lib/coursepick/gcp-credentials.json
    restart: unless-stopped
