services:
  backend:
    image: coursepicks/coursepick-backend:prod
    container_name: coursepick-backend
    ports:
      - '80:8080'
    env_file:
      - .env
    volumes:
      - /var/lib/coursepick/logs:/var/lib/coursepick/logs
    restart: unless-stopped
