services:
  backend:
    image: coursepicks/coursepick-backend:prod
    container_name: coursepick-backend
    ports:
      - '80:8080'
    environment:
      - 'PROD_PROFILE=${{ PROD_PROFILE }}'
      - 'PROD_DB_URL=${{ PROD_DB_URL }}'
      - 'PROD_DB_USERNAME=${{ PROD_DB_USERNAME }}'
      - 'PROD_DB_PASSWORD=${{ PROD_DB_PASSWORD }}'
      - 'PROD_MONGO_USERNAME=${{ PROD_MONGO_USERNAME }}'
      - 'PROD_MONGO_PASSWORD=${{ PROD_MONGO_PASSWORD }}'
      - 'ADMIN_TOKEN=${{ PROD_ADMIN_TOKEN }}'
      - 'GCP_DRIVE_FOLDER_ID=${{ GCP_DRIVE_FOLDER_ID }}'
      - 'GCP_CREDENTIALS_PATH=${{ GCP_CREDENTIALS_PATH }}'
    volumes:
      - /var/lib/coursepick/logs:/var/lib/coursepick/logs
    restart: unless-stopped
