name: coursepick-prod-lb

services:
  web:
    container_name: nginx
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-sub.conf:/etc/nginx/nginx-sub.conf
    restart: always
