name: coursepick-dev
services:

  mongodb:
    image: mongo:8.0.12
    container_name: mongodb
    ports:
      - '27017:27017'
    env_file:
      - .env
    volumes:
      - /var/lib/coursepick/mongo:/data/db
    restart: unless-stopped

  mysql:
    image: mysql:8.4.5
    container_name: mysql
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes:
      - /var/lib/coursepick/mysql:/var/lib/mysql
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - '8081:8081'
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mongodb

  backend:
    image: coursepicks/coursepick-backend:dev
    container_name: coursepick-backend
    ports:
      - '80:8080'
    env_file:
      - .env
    volumes:
      - /var/lib/coursepick/logs:/var/lib/coursepick/logs
      - /var/lib/coursepick/gcp-credentials.json:/var/lib/coursepick/gcp-credentials.json
    restart: unless-stopped
    depends_on:
      - mysql
      - mongodb
