name: coursepick-dev

services:
  backend:
    image: coursepicks/coursepick-backend:dev
    container_name: coursepick-backend
    ports:
      - '80:8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=${PROFILE}'
      - 'DB_URL=${DB_URL}'
      - 'DB_USERNAME=${DB_USERNAME}'
      - 'DB_PASSWORD=${DB_PASSWORD}'
      - 'MONGO_HOST=${MONGO_HOST}'
      - 'MONGO_PORT=${MONGO_PORT}'
      - 'MONGO_DATABASE=${MONGO_DATABASE}'
      - 'MONGO_USERNAME=${MONGO_USERNAME}'
      - 'MONGO_PASSWORD=${MONGO_PASSWORD}'
      - 'MONGO_AUTH_DATABASE=${MONGO_AUTH_DATABASE}'
      - 'ADMIN_TOKEN=${ADMIN_TOKEN}'
      - 'DEV_SERVER_URL=${DEV_SERVER_URL}'
      - 'PROD_SERVER_URL=${PROD_SERVER_URL}'
      - 'GCP_DRIVE_FOLDER_ID=${GCP_DRIVE_FOLDER_ID}'
      - 'GCP_CREDENTIALS_PATH=${GCP_CREDENTIALS_PATH}'
    depends_on:
      - mysql
      - mongodb
    volumes:
      - /var/lib/coursepick/logs:/var/lib/coursepick/logs
    restart: unless-stopped

  mongodb:
    image: mongo:8.0.12
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      - 'MONGO_INITDB_DATABASE=${MONGO_DATABASE}'
      - 'MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}'
    volumes:
      - /var/lib/coursepick/mongo:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - 'ME_CONFIG_MONGODB_SERVER=mongodb'
      - 'ME_CONFIG_MONGODB_PORT=27017'
      - 'ME_CONFIG_MONGODB_ENABLE_ADMIN=true'
      - 'ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_USERNAME}'
      - 'ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_PASSWORD}'
      - 'ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USERNAME}'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASSWORD}'
    depends_on:
      - mongodb # mongodb 서비스가 실행된 후에 실행되도록 의존성 설정

  mysql:
    image: 'mysql:8.4.5'
    environment:
      - 'MYSQL_DATABASE=${DB_DATABASE}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
      - 'MYSQL_USER=${DB_USERNAME}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'LANG=C.UTF-8'
      - 'LC_ALL=C.UTF-8'
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/coursepick/mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
