spring:
  config:
    activate.on-profile: prod
    import: classpath:monitoring-config.yml
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data.mongodb:
    host: ${MONGO_HOST}
    port: ${MONGO_PORT}
    database: ${MONGO_DATABASE}
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    authentication-database: ${MONGO_AUTH_DATABASE}
  batch:
    jdbc.initialize-schema: never
    job.enabled: false

springdoc:
  api-docs.enabled: false
  swagger-ui.enabled: false

osrm.url: ${OSRM_URL}
admin.token: ${ADMIN_TOKEN}
