spring:
  config.activate.on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "health, metrics"

admin.token: ${ADMIN_TOKEN}
