spring:
  config.activate.on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  web:
    resources:
      static-locations: none

gcp:
  drive.folder-id: ${GCP_DRIVE_FOLDER_ID}
  credentials.path: ${GCP_CREDENTIALS_PATH}

admin.token: ${ADMIN_TOKEN}
