spring:
  config.activate.on-profile: dev
  data.mongodb:
    host: mongodb
    port: 27017
    database: coursepick
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    authentication-database: admin

osrm.url: ${OSRM_URL}
admin:
  token: ${ADMIN_TOKEN}
  kakao-map-api-key: ${ADMIN_KAKAO_MAP_API_KEY}
jwt.secret-key: ${JWT_SECRET_KEY}
discord.webhook-url: ${DISCORD_WEBHOOK_URL}
gemini.api-key: ${GEMINI_API_KEY}
