spring:
  config.activate.on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

springdoc:
  dev-server-url: ${DEV_SERVER_URL}
  prod-server-url: ${PROD_SERVER_URL}

gcp:
  drive.folder-id: ${GCP_DRIVE_FOLDER_ID}
  credentials.path: ${GCP_CREDENTIALS_PATH}

admin.token: ${ADMIN_TOKEN}
