spring:
  config.activate.on-profile: prod
  data.mongodb:
    host: ${MONGO_HOST}
    port: 27017
    database: coursepick
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    authentication-database: admin

osrm.url: ${OSRM_URL}
admin:
  token: ${ADMIN_TOKEN}
  kakao-map-api-key: ${ADMIN_KAKAO_MAP_API_KEY}
jwt.secret-key: ${JWT_SECRET_KEY}
# 운영환경에서는 API 문서를 사용하지 않는다.
springdoc:
  api-docs.enabled: false
  swagger-ui.enabled: false
discord.webhook-url: ${DISCORD_WEBHOOK_URL}
gemini.api-key: ${GEMINI_API_KEY}

