name: coursepick-home-prod
services:

  mongodb:
    image: mongo:8.0.12
    container_name: coursepick-home-prod-mongodb
    env_file:
      - /var/lib/coursepick/env/.env.home-prod
    volumes:
      - mongodb_prod_data:/data/db
    restart: unless-stopped

  backend:
    image: coursepick-backend:home-prod
    container_name: coursepick-home-prod-backend
    build:
      context: ../..
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    restart: unless-stopped
    ports:
      - "8090:8080"
    env_file:
      - /var/lib/coursepick/env/.env.home-prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - /var/lib/coursepick/logs/home-prod:/var/lib/coursepick/logs
    depends_on:
      - mongodb

volumes:
  mongodb_prod_data:
