name: coursepick-prod-app
services:

  backend:
    image: coursepicks/coursepick-backend:prod
    container_name: coursepick-backend
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - OSRM_URL=${OSRM_URL}
      - JWT_SECRET_KEY=${JWT_SECRET}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    volumes:
      - /var/lib/coursepick/logs:/var/lib/coursepick/logs
      - /var/lib/coursepick/gcp-credentials.json:/var/lib/coursepick/gcp-credentials.json

  promtail:
    image: grafana/promtail:3.3.2
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./promtail.yml:/etc/promtail/promtail-config.yml
      - /var/lib/coursepick/logs:/app/logs:ro
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - backend
