name: coursepick-home-dev
services:

  mongodb:
    image: mongo:8.0.12
    container_name: coursepick-home-dev-mongodb
    environment:
      - MONGO_INITDB_DATABASE=coursepick
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_dev_data:/data/db
    restart: unless-stopped

  backend:
    image: coursepick-backend:home-dev
    container_name: coursepick-home-dev-backend
    build:
      context: ../..
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MONGO_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_ROOT_PASSWORD}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - ADMIN_KAKAO_MAP_API_KEY=${ADMIN_KAKAO_MAP_API_KEY}
      - OSRM_URL=${OSRM_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    volumes:
      - /var/lib/coursepick/logs/home-dev:/var/lib/coursepick/logs
    depends_on:
      - mongodb

volumes:
  mongodb_dev_data:
