name: Backend Home Prod Server CD

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_backend-home-deploy.yml
    secrets: inherit
    with:
      compose_project: coursepick-home-prod
      compose_file: etc/docker_compose/docker-compose.home-prod.yml
      health_port: 8090
      container_name: coursepick-home-prod-backend
