name: Backend CI

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ backend ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('backend/**/*.gradle*', 'backend/**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run tests
      run: ./gradlew test

    - name: Run code quality checks
      run: ./gradlew check

    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Gradle Tests
        path: backend/build/test-results/test/*.xml
        reporter: java-junit

    - name: Build with Gradle
      run: ./gradlew build
