name: Backend Image Push

on:
  pull_request:
    branches: [ backend ]

jobs:
  image-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('backend/**/*.gradle*', 'backend/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Run code quality checks
        run: ./gradlew check

      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Gradle Tests
          path: backend/build/test-results/test/*.xml
          reporter: java-junit

      - name: Build with Gradle
        run: ./gradlew build

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/coursepick-server:latest
            ${{ secrets.DOCKER_USERNAME }}/coursepick-server:${{ github.sha }}
          build-args: |
            PROFILE=${{ secrets.DEV_PROFILE }}
            DB_URL=${{ secrets.DEV_DB_URL }}
            DB_USERNAME=${{ secrets.DEV_DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}
